### ISSUE TITLE
current price is off by an hour

### ISSUE THREAD

**Issue by kasper-leFevre** [fbjerggaard/home-assistant-barry#2] opened 2022-01-06 07:33 UTC
If you are looking at the pictures you can se that current price 8.19 is showing 3.27. 
compared to the view from the app it the price between 7 and 8 and the correct price should be 3.60 between 8 and 9
<img width="658" alt="Screenshot 2022-01-06 at 08 27 19" src="https://user-images.githubusercontent.com/53400165/148345517-92f96cc7-8d71-44d1-af7e-99f736aac0e7.png">
![IMG_2791](https://user-images.githubusercontent.com/53400165/148345595-c12c01fd-4949-4065-8a01-4b29dbd17c52.PNG)

**Comment by fbjerggaard** [comment] 2022-01-07 16:52
I see. I found the issue and are running tests to see if it works as intended now - I'll push a change within a few days if it seems correct.

**Comment by fbjerggaard** [comment] 2022-01-12 16:17
Fixed in v0.0.4

**Closed as completed by fbjerggaard** 2022-01-12 16:17 UTC
